export enum Setting {
    MXB_TITLE = 'mxbcc.title',
    MXB_KEYWORDS = 'mxbcc.keywords',
    MXB_DESCRIPTION = 'mxbcc.description',
    MXB_ADDRESS = 'mxbcc.address',
    MXB_ADMIN_NAME = 'mxbcc.admin-name',
    MXB_ADMIN_EMAIL = 'mxbcc.admin-email',
    MXB_AVATAR = 'mxbcc.avatar',
    MXB_AVATAR_BG = 'mxbcc.avatar-background',
    MXB_QRCODE = 'mxbcc.qrcode',
    MXB_SCRIPT = 'mxbcc.script',
    MXB_NETEASE_COOKIE = 'mxbcc.netease.cookie',
    MXB_NETEASE_PLAYLIST_ID = 'mxbcc.netease.playlist-id',
    MXB_5SING_USERNAME = 'mxbcc.5sing.username',
    MXB_5SING_PASSWORD = 'mxbcc.5sing.password',
    MXB_5SING_TOKEN = 'mxbcc.5sing.token',
    MXB_5SING_USERID = 'mxbcc.5sing.user-id',
}
